name: Alpine Docker push

on:
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    permissions: write-all
    defaults:
      run:
        working-directory: './'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lower case
        id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: "ghcr.io/dopaemon/Storage:alpine"

      - name: Build, and push
        run: |
          rm -rf * .git .github
          git config --global credential.helper store
          git config --global user.name "dopaemon"
          git config --global user.email "polarisdp@gmail.com"
          git config --global core.editor "nano -w"
          git clone -b alpine --single-branch https://github.com/dopaemon/Docker.git ./
          docker build . --tag ${{ steps.string.outputs.lowercase }}
          docker push ${{ steps.string.outputs.lowercase }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
